#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ "$HOST" -eq gussy ]]; then
  export PATH=${HOME}/.npm-global/bin:$PATH
  # -- add Android
  export PATH=${HOME}/.npm-global/bin:$PATH
  export NODE_PATH=${HOME}/.npm-global/lib/node_modules:$PATH
fi

# -- add miniconda
export PATH=${HOME}/.miniconda/bin:$PATH

export PATH=$HOME/bin:$PATH
